version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: csharp_sample_solution_db
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data # 把 pgdata 掛到容器內 data 目錄
      - ./infra/db/postgres/init:/docker-entrypoint-initdb.d:ro
  #  redis:
  #    image: redis:7
  #    ports: [ "6379:6379" ]

volumes:
  pgdata: