worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream auth_service {
        server auth:8080;
    }

    upstream webapi_service {
        server webapi:8080;
    }

    upstream graphql_service {
        server graphql:8080;
    }

    server {
        listen 80;

        # Auth Service
        location /auth-service/ {
            proxy_pass         http://auth_service/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        # Web API Service
        location /webapi-service/ {
            proxy_pass         http://webapi_service/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        # GraphQL Service
        location /graphql {
            proxy_pass         http://graphql_service/graphql;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}
